// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {meta} from '../models';

export function LoadAppMeta():Promise<meta.MetaV1>;

export function SetBackgroundColor(arg1:string):Promise<Error>;
