// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadAppMeta() {
  return window['go']['meta']['MetaAPI']['LoadAppMeta']();
}

export function SetBackgroundColor(arg1) {
  return window['go']['meta']['MetaAPI']['SetBackgroundColor'](arg1);
}
