// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {board} from '../models';

export function InitMetaFiles():Promise<void>;

export function ListBoards():Promise<Array<board.BoardMetaData>>;

export function LoadBoard(arg1:number):Promise<board.Board>;

export function OpenWorkDir():Promise<void>;

export function SaveBoard(arg1:board.Board):Promise<number>;
