// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitMetaFiles() {
  return window['go']['app']['App']['InitMetaFiles']();
}

export function ListBoards() {
  return window['go']['app']['App']['ListBoards']();
}

export function LoadBoard(arg1) {
  return window['go']['app']['App']['LoadBoard'](arg1);
}

export function OpenWorkDir() {
  return window['go']['app']['App']['OpenWorkDir']();
}

export function SaveBoard(arg1) {
  return window['go']['app']['App']['SaveBoard'](arg1);
}
